name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-test-build:
    runs-on: ubuntu-latest
    name: Check, test and build
    env:
      RUST_BACKTRACE: full

    steps:
    - name:                      Checkout sources & submodules
      uses:                      actions/checkout@master
      with:
        fetch-depth:             5
        submodules:              recursive
# Check Stage
    - name:                      Checking rust-stable
      uses:                      actions-rs/cargo@master
      with:
        command:                 check
        toolchain:               stable
        args:                    --all --verbose

# Build Stage
    - name:                      Building rust-stable
      uses:                      actions-rs/cargo@master
      with:
        command:                 build
        toolchain:               stable
        args:                    --all --verbose

# Test Stage
    - name:                      Testing rust-stable
      uses:                      actions-rs/cargo@master
      with:
        command:                 test
        toolchain:               stable
        args:                    --all --verbose
